# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------
# Copyright (c) 2021
#
# See the LICENSE file for details
# see the AUTHORS file for authors
# ----------------------------------------------------------------------

# --------------------
# System wide imports
# -------------------

import os
import logging

# Typing hints
from argparse import ArgumentParser, Namespace

# ---------------------
# Thrid-party libraries
# ---------------------

import numpy as np

from lica.cli import execute
from lica.validators import vfile

import astropy.io.ascii
import astropy.units as u

from astropy.constants import astropyconst20 as const

from astropy.table import Table

# ------------------------
# Own modules and packages
# ------------------------

from ._version import __version__

# -----------------------
# Module global variables
# -----------------------

log = logging.getLogger(__name__)

# -----------------
# Matplotlib styles
# -----------------

# -------------------
# Auxiliary functions
# -------------------


# -----------------------
# AUXILIARY MAIN FUNCTION
# -----------------------

def plotdigitizer_to_ecsv(path: str, delimiter: str, x: str, y: str) -> Table:
    log.info("Converting PlotDigitizer generated %s, %s CSV to Table", x, y)
    table = astropy.io.ascii.read(
            path,
            delimiter=delimiter,
            data_start=1,
            names=(x, y),
            converters={x: np.float64, y: np.float64},
    )
    return table


def quantum_efficiency(table: Table) -> np.ndarray:
    """Computes the Quantum Efficiency given the Responsivity in A/W"""
    K = (const.h * const.c) / const.e
    return  (K * table["Responsivity"]  / table["Wavelength"].to(u.m)).to(u.dimensionless_unscaled)


def responsivity_to_ecsv(args: Namespace) -> None:
    table = plotdigitizer_to_ecsv(args.input_file, args.delimiter, args.x, args.y)
    table[args.x] = np.round(table[args.x], 0) * u.nm
    if args.normalized:
        table[args.y] = table[args.y] * u.dimensionless_unscaled
    else:
        table[args.y] = table[args.y] * u.ampere / u.watt
        if args.qe:
            table['QE'] = quantum_efficiency(table)
    log.info("Generated table is\n%s", table.info)
    output_path, _ = os.path.splitext(args.input_file)
    output_path += ".ecsv"
    log.info("Generating %s", output_path)
    table.write(output_path, overwrite=True)


def calibration_to_ecsv(args: Namespace) -> None:
    table = astropy.io.ascii.read(args.input_file, delimiter=";")
    log.info(table.info)


def readings_to_ecsv(args: Namespace) -> None:
    path = args.scan if args.scan else args.testbench
    if args.scan:
        log.info("Converting AutoScan CSV to Table")
        table = astropy.io.ascii.read(
            path,
            delimiter="\t",
            names=("Index", "Wavelength", "Current"),
        )
        table.remove_column("Index")
        table["Wavelength"] = np.round(table["Wavelength"], 0) * u.nm
        table["Current"] = table["Current"] * u.ampere
    else:
        log.info("Converting TestBench CSV to Table")
        table = astropy.io.ascii.read(
            path,
            delimiter=";",
            data_start=1,
            names=("Wavelength", "Current", "Read Noise"),
            converters={"Wavelength": np.float64, "Current": np.float64, "Read Noise": np.float64},
        )
        table["Wavelength"] = np.round(table["Wavelength"], 0) * u.nm
        table["Current"] = table["Current"] * u.ampere
        table["Read Noise"] = table["Read Noise"] * u.ampere
    log.info("Generated table is\n%s", table.info)
    output_path, _ = os.path.splitext(path)
    output_path += ".ecsv"
    log.info("Generating %s", output_path)
    table.write(output_path, overwrite=True)


# ===================================
# MAIN ENTRY POINT SPECIFIC ARGUMENTS
# ===================================

def add_args(parser: ArgumentParser) -> None:
    subparser = parser.add_subparsers(dest="command")
    parser_calib = subparser.add_parser("calibration", help="Photodiode calibration data CSV -> ECSV")
    parser_readings = subparser.add_parser("readings", help="Photodiode readings CSV -> ECSV")
    parser_responsivity = subparser.add_parser("responsivity", help="PlotDigitied Manufacturer Responsivity table CSV -> ECSV")

    # Readings Parser
    redex1 = parser_readings.add_mutually_exclusive_group(required=True)
    redex1.add_argument(
        "-a",
        "--scan",
        type=vfile,
        metavar="<CSV>",
        help="CSV was generated by LabView Scan utility",
    )
    redex1.add_argument(
        "-t",
        "--testbench",
        type=vfile,
        metavar="<CSV>",
        help="CSV was manually generated using LabView TestBench utility",
    )

    parser_responsivity.add_argument(
        "-i",
        "--input_file",
        type=vfile,
        metavar="<CSV>",
        help="CSV was manually generated using LabView TestBench utility",
    )
    parser_responsivity.add_argument(
        "-x",
        "--x",
        type=str,
        metavar="<X>",
        default="Wavelength", 
        help="X Column name (defaults to %(default)s)",
    )
    parser_responsivity.add_argument(
        "-y",
        "--y",
        type=str,
        metavar="<Y>",
        default="Responsivity",
        help="Y Column name (defaults to %(default)s)",
    )
    respex1 = parser_responsivity.add_mutually_exclusive_group()
    respex1.add_argument(
        "-n",
        "--normalized",
        action="store_true",
        help="Responsivity is normalized to 1.0",
    )
    respex1.add_argument(
        "-q",
        "--qe",
        action="store_true",
        help="Add Quantum Efficiency data to ECSV",
    )
    parser_responsivity.add_argument(
        "--delimiter",
        type=str,
        default=",",
        help="CSV delimiter (defaults to %(default)s)",
    )

# ================
# MAIN ENTRY POINT
# ================


COMMAND_TABLE = {
    "calibration": calibration_to_ecsv,
    "readings": readings_to_ecsv,
    "responsivity": responsivity_to_ecsv,
}


def ecsv(args: Namespace):
    COMMAND_TABLE[args.command](args)


def main():
    execute(
        main_func=ecsv,
        add_args_func=add_args,
        name=__name__,
        version=__version__,
        description="Convert CSV files to Astropy ECSV files",
    )
